# Generated by Django 5.2.16 on 2026-07-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('SPENDING_PATTERN', 'Spending Pattern'), ('FINANCIAL_RISK', 'Financial Risk'), ('DUPLICATE', 'Duplicate Detection'), ('COMPLIANCE', 'Compliance'), ('VENDOR', 'Vendor Risk'), ('BUDGET', 'Budget'), ('APPROVAL', 'Approval Workflow')], max_length=30)),
                ('description', models.TextField()),
                ('score', models.PositiveSmallIntegerField(default=10)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('recommendation', models.TextField()),
                ('threshold', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Rule',
                'verbose_name_plural': 'Business Rules',
                'ordering': ['category', 'code'],
            },
        ),
    ]
