# Generated by Django 5.2.16 on 2026-07-24 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_workflow_states'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transition', models.CharField(choices=[('SUBMITTED', 'Submitted for Review'), ('REVIEW_STARTED', 'Review Started'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned for Changes'), ('RESUBMITTED', 'Resubmitted'), ('AUTO_APPROVED', 'Auto-Approved by Rule Engine')], max_length=15)),
                ('from_status', models.CharField(blank=True, max_length=10)),
                ('to_status', models.CharField(max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('rule_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_audit_logs', to='expenses.expense')),
            ],
            options={
                'db_table': 'approval_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expense', '-created_at'], name='aal_expense_ts_idx')],
            },
        ),
    ]
