"""Professional PDF rendering for approved expense reports."""
from io import BytesIO
from xml.sax.saxutils import escape

from django.utils import timezone
from django.db.models import Avg, Count, Sum
from reportlab.lib import colors
from reportlab.lib.enums import TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


INK = colors.HexColor('#1C1A17')
MUTED = colors.HexColor('#6F6A62')
RULE = colors.HexColor('#DED9CF')
SURFACE = colors.HexColor('#F5F3EE')
ACCENT = colors.HexColor('#3F7259')


def _text(value):
    return escape(str(value or ''))


def _money(value, currency):
    return f'{currency} {float(value or 0):,.2f}'


def _footer(canvas, document):
    canvas.saveState()
    canvas.setStrokeColor(RULE)
    canvas.line(document.leftMargin, 13 * mm, A4[0] - document.rightMargin, 13 * mm)
    canvas.setFillColor(MUTED)
    canvas.setFont('Helvetica', 8)
    canvas.drawString(document.leftMargin, 8.5 * mm, 'Generated by Vyapar Margadarshan')
    canvas.drawRightString(A4[0] - document.rightMargin, 8.5 * mm, f'Page {document.page}')
    canvas.restoreState()


def _section_title(label, styles):
    return Paragraph(_text(label), styles['Section'])


def _table(data, widths, *, header=True, right_columns=()):
    style = [
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('GRID', (0, 0), (-1, -1), 0.35, RULE),
        ('LEFTPADDING', (0, 0), (-1, -1), 5),
        ('RIGHTPADDING', (0, 0), (-1, -1), 5),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
    ]
    if header:
        style.extend([
            ('BACKGROUND', (0, 0), (-1, 0), SURFACE),
            ('TEXTCOLOR', (0, 0), (-1, 0), INK),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('LINEBELOW', (0, 0), (-1, 0), 0.8, colors.HexColor('#BDB6A8')),
        ])
    for column in right_columns:
        style.append(('ALIGN', (column, 0), (column, -1), 'RIGHT'))
    return Table(data, colWidths=widths, repeatRows=1 if header else 0, hAlign='LEFT', style=TableStyle(style))


def build_expense_report_pdf(*, member, user, expenses, start_date, end_date, category, vendor, category_label):
    """Render a filtered, approved-only expense queryset to A4 PDF bytes."""
    currency = user.default_currency
    aggregate = expenses.aggregate(total=Sum('amount'), count=Count('id'), average=Avg('amount'))
    total = aggregate['total'] or 0
    count = aggregate['count'] or 0
    average = aggregate['average'] or 0
    category_rows = list(expenses.values('category').annotate(total=Sum('amount'), count=Count('id')).order_by('-total', 'category'))
    vendor_rows = list(expenses.exclude(vendor__isnull=True).exclude(vendor='').values('vendor').annotate(total=Sum('amount'), count=Count('id')).order_by('-total', 'vendor'))
    expense_rows = list(expenses.select_related('user').order_by('-date', '-created_at', '-id'))

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='Brand', parent=styles['Heading1'], fontName='Helvetica-Bold', fontSize=17, leading=20, textColor=INK, spaceAfter=2))
    styles.add(ParagraphStyle(name='ReportTitle', parent=styles['Heading2'], fontName='Helvetica', fontSize=11, leading=14, textColor=ACCENT, spaceAfter=10))
    styles.add(ParagraphStyle(name='Meta', parent=styles['BodyText'], fontName='Helvetica', fontSize=8.5, leading=12, textColor=MUTED))
    styles.add(ParagraphStyle(name='Section', parent=styles['Heading2'], fontName='Helvetica-Bold', fontSize=10.5, leading=13, textColor=INK, spaceBefore=9, spaceAfter=5))
    styles.add(ParagraphStyle(name='Cell', parent=styles['BodyText'], fontName='Helvetica', fontSize=8, leading=10, textColor=INK))
    styles.add(ParagraphStyle(name='CellRight', parent=styles['Cell'], alignment=TA_RIGHT))

    buffer = BytesIO()
    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=13 * mm,
        leftMargin=13 * mm,
        topMargin=13 * mm,
        bottomMargin=19 * mm,
        title='Vyapar Margadarshan Expense Report',
        author='Vyapar Margadarshan',
    )
    story = [
        Paragraph('Vyapar Margadarshan', styles['Brand']),
        Paragraph('Expense Report', styles['ReportTitle']),
        Paragraph(f'<b>Workspace:</b> {_text(member.organization.name)}', styles['Meta']),
        Paragraph(
            f'<b>Generated:</b> {timezone.localtime(timezone.now()).strftime("%Y-%m-%d %H:%M:%S %Z")}',
            styles['Meta'],
        ),
        Paragraph(
            f'<b>Report period:</b> {_text(start_date.isoformat() if start_date else "Beginning")} to '
            f'{_text(end_date.isoformat() if end_date else "Present")}',
            styles['Meta'],
        ),
        Paragraph(
            f'<b>Filters:</b> Category — {_text(category_label(category) if category else "All categories")}; '
            f'Vendor — {_text(vendor or "All vendors")}',
            styles['Meta'],
        ),
        Spacer(1, 5),
    ]

    top_category = category_rows[0] if category_rows else None
    top_vendor = vendor_rows[0] if vendor_rows else None
    summary_data = [
        ['Total approved spending', _money(total, currency), 'Approved expenses', str(count)],
        ['Average expense', _money(average, currency), 'Top category', category_label(top_category['category']) if top_category else 'Unavailable'],
        ['Top vendor', top_vendor['vendor'] if top_vendor else 'Unavailable', 'Data scope', 'Approved expenses only'],
    ]
    story.extend([
        _section_title('Summary', styles),
        _table(summary_data, [36 * mm, 50 * mm, 34 * mm, 59 * mm], header=False, right_columns=(1,)),
    ])

    category_data = [['Category', 'Expenses', 'Total', 'Share']]
    for row in category_rows:
        share = (float(row['total']) / float(total) * 100) if total else 0
        category_data.append([
            Paragraph(_text(category_label(row['category'])), styles['Cell']),
            str(row['count']),
            _money(row['total'], currency),
            f'{share:.1f}%',
        ])
    story.extend([
        _section_title('Category breakdown', styles),
        _table(category_data, [68 * mm, 28 * mm, 52 * mm, 31 * mm], right_columns=(1, 2, 3)),
    ])

    vendor_data = [['Vendor', 'Expenses', 'Total', 'Share']]
    for row in vendor_rows:
        share = (float(row['total']) / float(total) * 100) if total else 0
        vendor_data.append([
            Paragraph(_text(row['vendor']), styles['Cell']),
            str(row['count']),
            _money(row['total'], currency),
            f'{share:.1f}%',
        ])
    story.extend([
        _section_title('Vendor breakdown', styles),
        _table(vendor_data, [68 * mm, 28 * mm, 52 * mm, 31 * mm], right_columns=(1, 2, 3)),
    ])

    expense_data = [['Date', 'Title / Merchant', 'Category', 'Vendor', 'Amount', 'Status']]
    for expense in expense_rows:
        expense_data.append([
            expense.date.isoformat(),
            Paragraph(_text(expense.title), styles['Cell']),
            Paragraph(_text(category_label(expense.category)), styles['Cell']),
            Paragraph(_text(expense.vendor or '—'), styles['Cell']),
            Paragraph(_text(_money(expense.amount, currency)), styles['CellRight']),
            'Approved',
        ])
    story.extend([
        _section_title('Approved expenses', styles),
        _table(expense_data, [20 * mm, 43 * mm, 28 * mm, 38 * mm, 32 * mm, 23 * mm], right_columns=(4,)),
    ])

    document.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buffer.getvalue()
