"""
Rule Knowledge Base for expense anomaly detection.

Each rule defines: code, name, category, description, score contribution,
severity level, recommendation for the approver, and evidence fields used.
The rule engine evaluates expenses against these definitions.
"""

EXPENSE_REVIEW_RULES = {
    'HIGH_CATEGORY_AMOUNT': {
        'name': 'High Category Amount',
        'category': 'SPENDING_PATTERN',
        'description': 'Amount is unusually high compared to the category average.',
        'score': 25,
        'severity': 'HIGH',
        'recommendation': 'Compare the amount with recent category expenses and confirm business purpose.',
        'evidence_fields': ['amount', 'baseline_average', 'baseline_count', 'ratio'],
        'enabled': True,
        'version': '1.0',
    },
    'HIGH_VENDOR_AMOUNT': {
        'name': 'High Vendor Amount',
        'category': 'SPENDING_PATTERN',
        'description': 'Amount is unusually high compared to the vendor average.',
        'score': 15,
        'severity': 'MEDIUM',
        'recommendation': 'Verify the amount against prior purchases from the same vendor.',
        'evidence_fields': ['amount', 'baseline_average', 'baseline_count', 'ratio'],
        'enabled': True,
        'version': '1.0',
    },
    'HIGH_AMOUNT_CRITICAL': {
        'name': 'High Amount (Critical)',
        'category': 'FINANCIAL_RISK',
        'description': 'Amount is high and should be verified before approval.',
        'score': 25,
        'severity': 'HIGH',
        'recommendation': 'Verify amount, business purpose, and approval authority.',
        'evidence_fields': ['amount'],
        'threshold': 25000,
        'enabled': True,
        'version': '1.0',
    },
    'HIGH_AMOUNT_ELEVATED': {
        'name': 'High Amount (Elevated)',
        'category': 'FINANCIAL_RISK',
        'description': 'Amount is above the normal review threshold.',
        'score': 15,
        'severity': 'MEDIUM',
        'recommendation': 'Confirm the amount and business purpose before approval.',
        'evidence_fields': ['amount'],
        'threshold': 10000,
        'enabled': True,
        'version': '1.0',
    },
    'HIGH_AMOUNT_ROUTINE': {
        'name': 'High Amount (Routine Check)',
        'category': 'FINANCIAL_RISK',
        'description': 'Amount warrants a routine value check.',
        'score': 8,
        'severity': 'LOW',
        'recommendation': 'Perform a routine check on the amount.',
        'evidence_fields': ['amount'],
        'threshold': 5000,
        'enabled': True,
        'version': '1.0',
    },
    'MONTHLY_SPIKE': {
        'name': 'Monthly Spending Spike',
        'category': 'SPENDING_PATTERN',
        'description': 'User spending this month is significantly higher than their recent monthly average.',
        'score': 12,
        'severity': 'MEDIUM',
        'recommendation': 'Review total monthly spending to confirm all expenses are justified.',
        'evidence_fields': ['current_month_total', 'monthly_average', 'spike_ratio'],
        'threshold': 2.0,
        'enabled': True,
        'version': '1.0',
    },
    'CATEGORY_OUTLIER': {
        'name': 'Statistical Category Outlier',
        'category': 'SPENDING_PATTERN',
        'description': 'Amount is a statistical outlier for this category (z-score > 2 or above IQR upper fence).',
        'score': 15,
        'severity': 'MEDIUM',
        'recommendation': 'Compare this expense with typical category spending and verify the amount.',
        'evidence_fields': ['z_score', 'median', 'upper_fence', 'sample_size'],
        'enabled': True,
        'version': '1.0',
    },
    'DUPLICATE_CANDIDATE': {
        'name': 'Duplicate Candidate',
        'category': 'DUPLICATE',
        'description': 'A similar expense exists near the same date.',
        'score': 20,
        'severity': 'MEDIUM',
        'recommendation': 'Verify the receipt and confirm the expense is not a duplicate entry.',
        'evidence_fields': ['matching_expense_ids'],
        'enabled': True,
        'version': '1.0',
    },
    'MISSING_VENDOR': {
        'name': 'Missing Vendor',
        'category': 'COMPLIANCE',
        'description': 'Vendor information is missing or unclear.',
        'score': 10,
        'severity': 'LOW',
        'recommendation': 'Request complete vendor details before approval.',
        'evidence_fields': ['vendor'],
        'enabled': True,
        'version': '1.0',
    },
    'NEW_VENDOR': {
        'name': 'New Vendor',
        'category': 'VENDOR',
        'description': 'Vendor has no prior spend history in this scope.',
        'score': 5,
        'severity': 'LOW',
        'recommendation': 'Validate the new vendor and confirm business relationship.',
        'evidence_fields': ['vendor'],
        'enabled': True,
        'version': '1.0',
    },
    'MISSING_RECEIPT': {
        'name': 'Missing Receipt',
        'category': 'COMPLIANCE',
        'description': 'No receipt is attached to this expense.',
        'score': 20,
        'severity': 'MEDIUM',
        'recommendation': 'Ask the submitter to attach a receipt before approval.',
        'evidence_fields': ['receipt'],
        'enabled': True,
        'version': '1.0',
    },
    'WEAK_DESCRIPTION': {
        'name': 'Weak Description',
        'category': 'COMPLIANCE',
        'description': 'The business-purpose description is missing or too short.',
        'score': 10,
        'severity': 'LOW',
        'recommendation': 'Request a clear explanation of business purpose.',
        'evidence_fields': ['description'],
        'enabled': True,
        'version': '1.0',
    },
    'BUDGET_EXCEEDED': {
        'name': 'Budget Exceeded',
        'category': 'BUDGET',
        'description': 'This expense would take the applicable budget over its limit.',
        'score': 25,
        'severity': 'HIGH',
        'recommendation': 'Compare this expense with the available category budget before approval.',
        'evidence_fields': ['percentage'],
        'threshold': 100,
        'enabled': True,
        'version': '1.0',
    },
    'BUDGET_PRESSURE': {
        'name': 'Budget Pressure',
        'category': 'BUDGET',
        'description': 'This expense would use at least 80% of the applicable budget.',
        'score': 15,
        'severity': 'MEDIUM',
        'recommendation': 'Review remaining budget before approving additional expenses.',
        'evidence_fields': ['percentage'],
        'threshold': 80,
        'enabled': True,
        'version': '1.0',
    },
    'OLD_PENDING_EXPENSE': {
        'name': 'Old Pending Expense',
        'category': 'APPROVAL',
        'description': 'Expense has been waiting for review for too long.',
        'score': 10,
        'severity': 'LOW',
        'recommendation': 'Follow up on the approval delay and process the expense.',
        'evidence_fields': ['pending_days'],
        'threshold': 7,
        'enabled': True,
        'version': '1.0',
    },
}

RULE_CATEGORIES = {
    'SPENDING_PATTERN': 'Spending Pattern',
    'FINANCIAL_RISK': 'Financial Risk',
    'DUPLICATE': 'Duplicate Detection',
    'COMPLIANCE': 'Compliance',
    'VENDOR': 'Vendor Risk',
    'BUDGET': 'Budget',
    'APPROVAL': 'Approval Workflow',
}
