# Generated by Django 5.2.16 on 2026-07-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0002_activitylog_act_org_action_ts_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('EXPENSE_CREATED', 'Expense Created'), ('EXPENSE_UPDATED', 'Expense Updated'), ('EXPENSE_DELETED', 'Expense Deleted'), ('EXPENSE_SUBMITTED', 'Expense Submitted'), ('EXPENSE_APPROVED', 'Expense Approved'), ('EXPENSE_REJECTED', 'Expense Rejected'), ('EXPENSE_RETURNED', 'Expense Returned'), ('EXPENSE_REVIEW_STARTED', 'Expense Review Started'), ('BUDGET_CREATED', 'Budget Created'), ('BUDGET_UPDATED', 'Budget Updated'), ('BUDGET_DELETED', 'Budget Deleted'), ('MEMBER_INVITED', 'Member Invited'), ('MEMBER_JOINED', 'Member Joined'), ('ROLE_CHANGED', 'Role Changed'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout')], max_length=50),
        ),
    ]
